// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTMERuaD0VIPPVwODUuUT3--uzfP27P4',
    appId: '1:84656227361:web:a2596488b9445def9bcf60',
    messagingSenderId: '84656227361',
    projectId: 'alchemist-bathery',
    authDomain: 'alchemist-bathery.firebaseapp.com',
    storageBucket: 'alchemist-bathery.appspot.com',
    measurementId: 'G-753HPMX913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqm8aZcC8lO8UZp3rXatPnJkcxXSVzAg',
    appId: '1:84656227361:android:b831659844a7300e9bcf60',
    messagingSenderId: '84656227361',
    projectId: 'alchemist-bathery',
    storageBucket: 'alchemist-bathery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbft0mqyCva9cID3UjnGg3PhqtoUkEnl8',
    appId: '1:84656227361:ios:ef7477eb6a3adfa19bcf60',
    messagingSenderId: '84656227361',
    projectId: 'alchemist-bathery',
    storageBucket: 'alchemist-bathery.appspot.com',
    iosBundleId: 'com.example.student',
  );
}
